update docker compose
TykTechnologies/tyk-pro-docker-demo pull request #30
Opened 2021-08-11 05:44 UTC by jonathanbernal25

docker-compose.yml in **mdcb** branch under the **tyk-mdcb** service is creating a directory with the name of tyk_sink.conf, then erroring out due to the volume mapping trying to map a directory to a file. 

Updated the compose file to prevent such error.
<img width="1784" alt="Screenshot 2021-08-11 at 1 43 07 PM" src="https://user-images.githubusercontent.com/47840430/128975816-bf5e7ca7-7726-441d-97cd-14c3ed27761a.png">

2021-09-30 06:20 UTC, alephnull commented
Is this repo still used? This PR keeps getting posted to the #devops channel but we do not use this repo.

2021-10-21 19:15 UTC, sedkis commented
Yes, we use this extensively for people who want a lightweight version of Tyk pro to run quickly for PoC purposes

2021-10-21 19:17 UTC, sedkis requested changes

2021-10-21 19:17 UTC, sedkis commented on README.md
> +git checkout improve-mdcb
this is wrong rightt?  We want to still checckoutt `mdcb` after the merge is complete?

2021-10-21 19:17 UTC, sedkis commented on README.md
> +git checkout improve-mdcb
same here @jonathanbernal25

2022-01-19 11:55 UTC, closed without merging